name: CI
on: [push]
jobs:
  build:
    name: Build & Publish Next
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN:  ${{ secrets.NPM_AUTH_TOKEN }}  
    steps:
      - run: |
          echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >>~/.npmrc
          yarn install
          yarn build
          yarn publish --tag next --new-version 1.0.0-$(date +%s) --non-interactive
